{
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "SOURCE", "query": "influxdb" },
   { "name": "bucket", "label": "BUCKET", "query": "buckets()" },
   {
    "name": "adapter",
    "label": "ADAPTER",
    "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"adapter\")\r\n|> keyValues(keyColumns: [\"name\"])\r\n|> group()\r\n|> keep(columns: [\"name\"])"
   },
   {
    "name": "stream",
    "label": "STREAM",
    "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"stream\")\r\n|> keyValues(keyColumns: [\"name\"])\r\n|> group()\r\n|> keep(columns: [\"name\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Average CPU usage.\nThe System CPU usage is for all cores. Max value is number of cores multiplied by 100\nThe App CPU usage is for all threads on all cores and relative to System CPU usage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "fields = [\"sys_cpu\", \"app_cpu\"]\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"sysinfo\" and contains(value: r._field, set: fields))\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n|> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "The System Memory Usage - is total memory usage by all processes\nThe App Memory Usage - is total memory usage by all threads. Value is relative to total system momory",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "fields = [\"sys_mem\", \"app_mem\"]\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"sysinfo\" and contains(value: r._field, set: fields))\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n|> yield(name: \"mean\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\r\nfields = [\"app_uptime\", \"sys_uptime\"]\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"sysinfo\" and contains(value: r._field, set: fields))\r\n|> map(fn: (r) => ({\r\n    r with\r\n        _value: string(\r\n            v: duration(\r\n                v: uint(\r\n                    v: date.truncate(\r\n                        t: time(\r\n                            v: uint(v: r._value) * uint(v: 60000000000)\r\n                        ),\r\n                        unit: if r._value >= 10080 then 1d else if r._value >= 1440 then 1h else 1m,\r\n                    )\r\n                )\r\n            )\r\n        ),\r\n}))\r\n|> aggregateWindow(every: v.windowPeriod, fn: last)\r\n|> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "fields = [\"la1\", \"la5\", \"la15\"]\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"sysinfo\" and contains(value: r._field, set: fields))\r\n|> aggregateWindow(every: v.windowPeriod, fn: last)\r\n|> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Streams",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"stream\")\r\n|> drop(columns: [\"_measurement\", \"_start\", \"_stop\", \"id\"])\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> filter(fn: (r) => r.active == true and r.onair == false)\r\n|> sort(columns: [\"_time\"], desc: true)\r\n|> limit(n: 1)\r\n|> map(fn: (r) => ({\r\n    r with\r\n        elapsed:\r\n            uint(v: date.truncate(t: now(), unit: 1m)) -\r\n            uint(v: date.truncate(t: r._time, unit: 1m)),\r\n}))\r\n|> drop(columns: [\"_time\", \"active\", \"onair\", \"packets\"])\r\n|> group()\r\n|> sort(columns: [\"elapsed\"])\r\n|> map(fn: (r) => ({\r\n    r with\r\n        elapsed: string(v: duration(v: r.elapsed)),\r\n}))\r\n|> yield(name: \"last\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${adapter}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "repeat": "adapter",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "fields = [\"signal\", \"snr\", \"ber\", \"unc\"]\nfrom(bucket: \"${bucket}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"adapter\" and r.name == \"${adapter}\")\n|> filter(fn: (r) => contains(value: r._field, set: fields))\n|> drop(columns: [\"id\", \"name\"])\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\n|> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "${stream}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "repeat": "stream",
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "fields = [\"bitrate\", \"sync_error\", \"pes_error\", \"cc_error\", \"sc_error\"]\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r._measurement == \"stream\" and r.name == \"${stream}\" and contains(value: r._field, set: fields))\r\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n|> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n|> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}