name: Development build
run-name: 🚀 ${{ github.actor }} - ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - dev**
    paths-ignore:
      - '**/README.md'

env:
  VERSION_NODE: 22.x
  IMAGE_NAME: cesbo/senta-help
  IMAGE_REGISTRY_URL: 103.249.134.120:5000

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.VERSION_NODE }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  publish-docker:
    runs-on: ubuntu-latest
    name: Publish to Docker
    env:
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Configure Docker to use insecure registry
        run: |
          echo '{"insecure-registries": ["${{ env.IMAGE_REGISTRY_URL }}"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare the image tag
        run: |
          export IMAGE_TAG=$(echo "$BRANCH_NAME" | sed 's/[\/\\]/-/g')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: 🛠️ Build Docker image
        run: |
          docker build \
            --load \
            --file ./deploy/Dockerfile \
            --tag ${{ env.IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --tag ${{ env.IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest \
            .
      - name: Check Docker Registry
        run: curl -v ${{ env.IMAGE_REGISTRY_URL }}/v2/
      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
